### ISSUE TITLE
Bad download of preview files

### ISSUE THREAD

**Issue by Pushkin31** [dracula/mixplorer#8] opened 2023-02-17 12:54 UTC
Hello.
For a very long time I have been facing the problem of bad loading of preview apk files with this theme. I thought mixplorer was the problem, but after using a dozen of other themes, I found out that it was the dracula theme.
On my own, I could not figure out what is the cause, I hope you can do it!

<details>
<summary>screen</summary>

![Screenshot_20230217-155203](https://user-images.githubusercontent.com/35974828/219658332-ef02041c-e51c-48ac-b2eb-eb0483a90c8c.png)
![Screenshot_20230217-155209](https://user-images.githubusercontent.com/35974828/219658350-364e3cd2-3768-4dbf-834e-8fb87a26167c.png)

</details>

After I logged into the folder, I have to refresh it forcibly to make the previews appear...

Android: 13
Device: Google Pixel 5a

**Comment by Pushkin31** [comment] 2023-02-17 14:55
+ Added WhatsApp, Telegram, Twitter, Instagram icon. because developer added new bookmarks.

**Comment by sionta** [comment] 2023-02-22 05:02
What version do you use?

**Comment by Pushkin31** [comment] 2023-02-24 14:24
> What version do you use?

Mix – 6.30.3 silver
Theme – 1.2.0 (last version)

**Comment by sionta** [comment] 2023-02-27 01:47
> > What version do you use?
> 
> Mix – 6.30.3 silver Theme – 1.2.0 (last version)

Thank you, I will fix it ASAP! 🙏

**Comment by sionta** [comment] 2023-03-01 15:09
> > What version do you use?
> 
> Mix – 6.30.3 silver Theme – 1.2.0 (last version)

have you tried resetting mixplorer to default?

**Comment by Pushkin31** [comment] 2023-03-01 15:17
> > > What version do you use?
> > 
> > Mix – 6.30.3 silver Theme – 1.2.0 (last version)
> 
> have you tried resetting mixplorer to default?

Yes, of course. Also tried different versions: silver and xda.

**Comment by sionta** [comment] 2023-03-01 15:28
> > > > What version do you use?
> > > 
> > > 
> > > Mix – 6.30.3 silver Theme – 1.2.0 (last version)
> > 
> > 
> > have you tried resetting mixplorer to default?
> 
> Yes, of course. Also tried different versions: silver and xda.

did you find any `.nothumbnail` file in the folder?

**Comment by Pushkin31** [comment] 2023-03-01 17:44
No, there is no such file. If it were so, then all the other themes would also have chosen bad previews, but this only happens to me with the dracula theme ... Now I'm using another theme, everything is fine.

**Comment by Pushkin31** [comment] 2023-03-01 17:44
No, there is no such file. If it were so, then all the other themes would also have chosen bad previews, but this only happens to me with the dracula theme ... Now I'm using another theme, everything is fine.

**Comment by sionta** [comment] 2023-03-02 15:22
> No, there is no such file. If it were so, then all the other themes would also have chosen bad previews, but this only happens to me with the dracula theme ... Now I'm using another theme, everything is fine.

Ok, I've tried on several devices all seem fine. but calm down I will try to find the cause and if necessary I will release it to the latest version so please wait.

**Comment by sionta** [comment] 2023-06-30 10:45
> ++ Added WhatsApp, Telegram, Twitter, Instagram icon. because developer added new bookmarks.
> 

Hey how are you, please share your email address to try a theme that I have not committed and published publicly and give me your review or criticism in the email.

**Comment by Pushkin31** [comment] 2023-06-30 16:22
> > ++ Added WhatsApp, Telegram, Twitter, Instagram icon. because developer added new bookmarks.
> > 
> 
> Hey how are you, please share your email address to try a theme that I have not committed and published publicly and give me your review or criticism in the email.

Send me your email, I'll write to you. I just do not want to distribute my mail in the public domain :)

**Comment by Pushkin31** [comment] 2023-06-30 16:22
> > ++ Added WhatsApp, Telegram, Twitter, Instagram icon. because developer added new bookmarks.
> > 
> 
> Hey how are you, please share your email address to try a theme that I have not committed and published publicly and give me your review or criticism in the email.

Send me your email, I'll write to you. I just do not want to distribute my mail in the public domain :)

**Comment by sionta** [comment] 2023-07-03 11:49
> > > ++ Added WhatsApp, Telegram, Twitter, Instagram icon. because developer added new bookmarks.
> > > 
> > 
> > Hey how are you, please share your email address to try a theme that I have not committed and published publicly and give me your review or criticism in the email.
> 
> Send me your email, I'll write to you. I just do not want to distribute my mail in the public domain :)

4nd123@protonmail.com

**Comment by sionta** [comment] 2023-07-16 06:38
Hei sir

**Closed** 2023-07-16 06:38 UTC
Labels: enhancement, wontfix, bugfix

**Comment by sionta** [comment] 2023-07-21 20:02
https://github.com/dracula/mixplorer/releases/tag/v1.3.0
